import 'package:adope/core/model/hive_model.dart';

final List<PetModel> petsList = [
  PetModel(
    name: "Muana",
    age: 1,
    imagePath: "https://images.pexels.com/photos/2607544/pexels-photo-2607544.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 1099,
    gender: Gender.male,
    id: 0,
  ),
  PetModel(
    name: "Carry",
    age: 1.5,
    imagePath: "https://images.pexels.com/photos/1933464/pexels-photo-1933464.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 900,
    gender: Gender.female,
    id: 1,
  ),
  PetModel(
    name: "Daine",
    age: 2.8,
    imagePath: "https://images.pexels.com/photos/2774140/pexels-photo-2774140.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 2999,
    gender: Gender.female,
    id: 2,
  ),
  PetModel(
    name: "Toby",
    age: 2,
    imagePath: "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 1999,
    gender: Gender.male,
    id: 3,
  ),
  PetModel(
    name: "Bruce",
    age: 2.1,
    imagePath: "https://images.pexels.com/photos/15347387/pexels-photo-15347387.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 13000,
    gender: Gender.male,
    id: 4,
  ),
  PetModel(
    name: "Dober",
    age: 5,
    imagePath: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 1099,
    gender: Gender.male,
    id: 5,
  ),
  PetModel(
    name: "Dunno",
    age: 2.1,
    imagePath: "https://images.pexels.com/photos/1254140/pexels-photo-1254140.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 5600,
    gender: Gender.male,
    id: 6,
  ),
  PetModel(
    name: "Craige",
    age: 0.8,
    imagePath: "https://images.pexels.com/photos/39317/chihuahua-dog-puppy-cute-39317.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 2999,
    gender: Gender.female,
    id: 7,
  ),
  PetModel(
    name: "Runo",
    age: 2,
    imagePath: "https://images.pexels.com/photos/58997/pexels-photo-58997.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 1999,
    gender: Gender.male,
    id: 8,
  ),
  PetModel(
    name: "Bruno",
    age: 2.1,
    imagePath: "https://images.pexels.com/photos/2253275/pexels-photo-2253275.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 13000,
    gender: Gender.male,
    id: 9,
  ),
  PetModel(
    name: "Hobo",
    age: 5,
    imagePath: "https://images.pexels.com/photos/731022/pexels-photo-731022.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 1230,
    gender: Gender.female,
    id: 10,
  ),
  PetModel(
    name: "Kruger",
    age: 2.8,
    imagePath: "https://images.pexels.com/photos/1490908/pexels-photo-1490908.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 5600,
    gender: Gender.male,
    id: 11,
  ),
  PetModel(
    name: "Belly",
    age: 0.8,
    imagePath: "https://images.pexels.com/photos/1629781/pexels-photo-1629781.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 2999,
    gender: Gender.male,
    id: 12,
  ),
  PetModel(
    name: "Appu",
    age: 2,
    imagePath: "https://images.pexels.com/photos/257540/pexels-photo-257540.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 1999,
    gender: Gender.male,
    id: 13,
  ),
  PetModel(
    name: "Raja",
    age: 2.1,
    imagePath: "https://images.pexels.com/photos/59523/pexels-photo-59523.jpeg?auto=compress&cs=tinysrgb&w=1600",
    isAdopted: false,
    price: 13000,
    gender: Gender.male,
    id: 14,
  ),
];

const String dummyText =
    "He/She is a playful and energetic Golden Retriever puppy who loves exploring his surroundings and meeting new people. He has a soft and fluffy coat that's always getting him compliments, and he's always up for a good game of fetch or tug-of-war. Max is still in the process of being potty trained, but he's making great progress and already knows how to sit and come when called. He's a curious and affectionate pup who's eager to learn and grow with his new family.";
